// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaG8AF4Jyu_Wa0FCguBCz-hrcDbAeZH4E',
    appId: '1:106498279432:web:76cbe1ae5295cb7ae3a9bd',
    messagingSenderId: '106498279432',
    projectId: 'whatsapp-backend-30b90',
    authDomain: 'whatsapp-backend-30b90.firebaseapp.com',
    storageBucket: 'whatsapp-backend-30b90.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjei9dwUIQAneneRDvhhvTyFtKplCaEYU',
    appId: '1:106498279432:android:0f2aa2f3e7a1ec30e3a9bd',
    messagingSenderId: '106498279432',
    projectId: 'whatsapp-backend-30b90',
    storageBucket: 'whatsapp-backend-30b90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr6xsCop_XbNZLmXE9g9NuIjrV7WU1hdA',
    appId: '1:106498279432:ios:35290addefdeb1c1e3a9bd',
    messagingSenderId: '106498279432',
    projectId: 'whatsapp-backend-30b90',
    storageBucket: 'whatsapp-backend-30b90.appspot.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
